### ISSUE TITLE
Any documentation how to use DialogueChoice?

### ISSUE THREAD

**Issue by jeansusgodney** [DoublSB/UnityDialogAsset#1]
Hi I just downloaded the asset and so far it works really well.

I want to implement choice system to the dialog manager and didn't find any documentation regarding this topic and I wonder if this kind of scenario is supported.

I saw there's a class called DialogueChoice. Does this work for my scenario? Looking forward to your reply. <3 Xoxo

**Comment by DoublSB** [comment]
Hello, jeansusgodney. Thank you for using my asset.

You said asset has a 'Dialogue Choice' class, but I didn't make any class for the choice system.
So I can't advise on that for now, but I'll take your idea and implement the choice system in next version.

I will try to update it in early October. Have a nice day : )

**Comment by jeansusgodney** [comment]
I see that the class comes from another paid asset when I googled the class name. But it would be great to see examples of this scenario

**Comment by DoublSB** [comment]
7e94a8b

I updated asset that contains choice system.
Although this issue has been open for a long time, I hope this update is helpful for you.

Update for Asset store is under review now, so please download from Git if you want to apply it immediately.
If you want to know how to use it, check the [documentation](https://github.com/DoublSB/UnityDialogAsset#selection).

**Comment by jeansusgodney** [comment]
Hi thanks. I will look at it and give any feedback if needed
